version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pedidos-postgres
    environment:
      POSTGRES_DB: pedidos_db
      POSTGRES_USER: pedidos_user
      POSTGRES_PASSWORD: pedidos_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pedidos_user -d pedidos_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: pedidos-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/pedidos_db
      KC_DB_USERNAME: pedidos_user
      KC_DB_PASSWORD: pedidos_pass

    ports:
      - "8080:8080"

    command:
      - start-dev
      - --import-realm

    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: